language: node_js

node_js:
  - "8"

cache:
  directories:
    - "DjangoGirls/turorial"

install:
  - npm install gitbook-cli -g
  - gitbook install

script: gitbook build

branches:
  except:
  - crowdin_master
